# Generated by Django 6.0.1 on 2026-01-30 04:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_review_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('service', 'customer')},
        ),
        migrations.RemoveField(
            model_name='review',
            name='booking',
        ),
    ]
